name: Build And Run Java
# events
on:
  push:
    branches:
      - main
jobs:
  build_and_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # clone repo to run operation

      - name: Set up # set up programming language version
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt' 

      - name: Build # B
        run: cd src && javac Main.java
        shell: bash

      - name: Run
        run: cd src && java Main
        shell: bash